import type { Metadata } from "next";
import "./globals.css";
import { poppins_regular } from "./ui/font";
import { poppins_medium } from "./ui/font";
import { poppins_black } from "./ui/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins_regular} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
