import type { Metadata } from "next";
import "./globals.css";
import { 
  poppins

} from "./ui/font";
import { SessionProvider } from "next-auth/react";
import { getSession } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getSession();
  return (
    <html lang="en">
      <body
        className={`${poppins} antialiased`}
      >
        {/* <SessionProvider session={session}> */}
        <SessionProvider>
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
